using HonestAuto.Data;
using HonestAuto.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

//Auto - Generated by Visual Studio and partially edited by me
namespace HonestAuto.Controllers
{
    public class MessageConversationController : Controller
    {
        private readonly MarketplaceContext _context;

        public MessageConversationController(MarketplaceContext context)
        {
            _context = context;
            // Constructor for MessageConversationController that takes an instance of MarketplaceContext.
        }

        // INDEX (Read/List all)
        public IActionResult Index()
        {
            var conversations = _context.MessageConversations.ToList();
            // Retrieve all message conversations from the database and convert them to a list.
            return View(conversations);
            // Return a view with the list of message conversations.
        }

        // CREATE (GET)
        public IActionResult Create()
        {
            return View();
            // Display the Create view for creating a new message conversation.
        }

        // CREATE (POST)
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(MessageConversation conversation)
        {
            if (ModelState.IsValid)
            {
                _context.Add(conversation);
                await _context.SaveChangesAsync();
                // If the model is valid, add the message conversation to the database and save changes.
                return RedirectToAction(nameof(Index));
                // Redirect to the Index action after successfully creating the conversation.
            }
            return View(conversation);
            // If the model is not valid, return the Create view with validation errors.
        }

        // EDIT (GET)
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var conversation = await _context.MessageConversations.FindAsync(id);
            if (conversation == null)
            {
                return NotFound();
            }
            return View(conversation);
            // Display the Edit view for editing an existing message conversation.
        }

        // EDIT (POST)
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("MessageConversationID,Content,TimeStamp,UserID1,UserID2")] MessageConversation conversation)
        {
            if (id != conversation.MessageConversationID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(conversation);
                    await _context.SaveChangesAsync();
                    // If the model is valid, update the message conversation in the database and save changes.
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_context.MessageConversations.Any(c => c.MessageConversationID == conversation.MessageConversationID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
                // Redirect to the Index action after successfully editing the conversation.
            }
            return View(conversation);
            // If the model is not valid, return the Edit view with validation errors.
        }

        // DELETE (GET)
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var conversation = await _context.MessageConversations.FindAsync(id);
            if (conversation == null)
            {
                return NotFound();
            }
            return View(conversation);
            // Display the Delete view for deleting an existing message conversation.
        }

        // DELETE (POST/Confirmed)
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var conversation = await _context.MessageConversations.FindAsync(id);
            if (conversation == null)
            {
                return NotFound();
            }
            _context.MessageConversations.Remove(conversation);
            await _context.SaveChangesAsync();
            // Remove the message conversation from the database and save changes.
            return RedirectToAction(nameof(Index));
            // Redirect to the Index action after successfully deleting the conversation.
        }
    }
}